### PR TITLE
Deprecate inclusion of main namespace module. Prefer inclusion of Ver…

### PR DESCRIPTION
**Pull request by tmertens**
…balize::Action instead

@taylorzr

### CODE REVIEW

**Comment by taylorzr** [comment]
The more I think about this, the more I don't think we should do it yet. We don't have a use case for including anything other than the standard action right now. So this adds complexity that is not necessary right now.

**Comment by tmertens** [comment]
There is no added complexity here, only a change in namespacing, which sets it up for long-term success.  There will be substantially more resistance to changing this in the future when it is more widely used across more/many projects/users.  In general, it is an antipattern that we are including a base module into other classes which itself also includes many other classes within itself.

Here is exactly why it should change:

```ruby
require 'verbalize'
class A
  include Verbalize
end

A.constants
# => [:VERSION, :BuildInitializeMethod, :BuildSafeActionMethod, :BuildDangerousActionMethod, :BuildAttributeReaders, :Result, :VerbalizeError, :ClassMethods]

**Comment by tmertens** [comment]
Versus:

```ruby
class A
  include Verbalize::Action
end
A.constants
# => [:THROWN_SYMBOL, :ClassMethods] 
```

**Comment by taylorzr** [comment]
There is added complexity in deprecating, and supporting both inclusions for now. I know it's very low complexity, but I don't see any need for this right now. So to me this is just incidental complexity. And since we don't have any use cases, it feels like we're trying to predict the future.

The base Verbalize module doesn't include anything extra in it, unless you're referring to the other classes/modules namespaced under it.

With that said, I think these are relatively minor gripes that shouldn't block, so feel free to merge.

**Pull request merged**
