### PR TITLE
Redo: Update compatibility ruby 2 7

### PR DESCRIPTION
**Pull request by tremulaes**

### CODE REVIEW

**Comment by tremulaes** [comment]
@taylorzr I wanted to test out a fix for this following the [official ruby-lang recommendations](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) but it is pretty ugly. Let me know what you think, I'm happy to make whatever changes I can but I'm not sure where next to go with this particular compatibility issue.

image

**Review by Kuraiou — APPROVED** [review]
:tiger: HI CHRIS -- this is perfect timing, we were planning on working on this ourselves this sprint!

**Comment by tremulaes** [comment]
@Kuraiou HI!

Glad to be helpful. I use Verbalize a lot still, it's been a terrific tool and I am looking forward to getting rid of these warnings haha

**Review by taylorzr — APPROVED** [review]
lgtm, thanks @tremulaes !!

**Comment by taylorzr** [comment]
Pushed to 2.3.1 to rubygems

**Pull request merged**
